### ISSUE TITLE
[Question] Leaflet.draw...dead?

### ISSUE THREAD

**Issue by mechevarria** [Asymmetrik/ngx-leaflet-draw#94]
Just a question. [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) has not had any contributions in at least a couple years. Are there any plans to move this draw wrapper or add another wrapper for an active drawing plugin?

For example, the [leaflet-geoman](https://github.com/geoman-io/leaflet-geoman) plugin seems to be active.

**Comment by reblace** [comment]
AFAICT Leaflet.draw is no longer active. I noticed that a while ago as well.
Writing a wrapper for leaflet-geoman is on the todo list.

**Comment by hlovdal** [comment]
[Leaflet-Euclides](https://github.com/gabriel-russo/leaflet-euclides) is a fork of leaflet-draw, it is 28 commits ahead of the upstream project, and it has been updated as recently as 4 months ago. It is published under [its own name](https://www.npmjs.com/package/leaflet-euclides).

Since this is a fork I suspect this to be much less work to switch to than a completely different library.
